version: "3.8"

# This file extends docker-compose.prod.yml with staging-specific configurations
# Use with: docker-compose -f docker-compose.prod.yml -f docker-compose.staging.yml up -d

services:
  app:
    environment:
      - NODE_ENV=staging
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-ai-agent-generator-staging}
      - LOG_LEVEL=debug
      - ENABLE_API_DEBUGGING=true
    deploy:
      replicas: 1 # Fewer replicas for staging

  redis:
    command: redis-server --appendonly yes --loglevel verbose
    ports:
      - "6379:6379" # Expose Redis port in staging for debugging

  nginx:
    volumes:
      - ./nginx/conf.d/staging.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80" # Use different ports for staging
      - "8443:443" # Use different ports for staging
    environment:
      - NGINX_HOST=staging.example.com
      - NGINX_PORT=8080

  # Additional service for staging environment
  monitoring:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - app
      - redis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  prometheus-data:
